### ISSUE TITLE
Cannot Get Data

### ISSUE THREAD

**Issue by tomasbek** [ManifestoProject/manifestoR#1]
Hello,

When I try to download election programmes data (I use OSX), I get this error:

**Error in curl::curl_fetch_memory(url, handle = handle)
Number of redirects hit maximum amount**

Do I need to have install any other packages to make this work? 

Thanks

**Comment by jirkalewandowski** [comment]
Hi tomasbek,

we know this error message appears when a version of the dataset is requested, which is not in our database or the name is misspelled. You get a list of available versions from `mp_coreversions()`. The value in `datasets.id` is what you need to request. If this does not solve your problem, could you please:
1. Check whether you have manifestoR version 1.0-5 *`sessionInfo()` and if not upgrade to that?
2. Try whether the code `mp_maindataset("MPDS2014a")` produces the same error on your system?
3. If yes, try whether the code `mp_maindataset()` produces the same error on your system?
4. If still yes, post the code you are executing or a minimum example of code that produces the error on your system?

Thanks,

Jirka

**Comment by tomasbek** [comment]
Dear Jirka, thanks for your response. I have tried entering all of your suggested codes but nothing helped. Here is a printout of the output:

![code](https://cloud.githubusercontent.com/assets/14822950/10104421/36e7a0e4-63b2-11e5-9cb1-913597c364da.jpg)

**Comment by jirkalewandowski** [comment]
Thanks. I can reproduce this behavior if I specify an invalid API key in `mp_setapikey`. Can you please double check that with the API key you see on your profile page on manifesto-project.wzb.eu ? If you experience trouble with that and post more code, please make sure to not post you API key here for security reasons.

I will correct the error message for the case of an invalid API key in the next release of manifestoR.

**Comment by tomasbek** [comment]
Jirka, that actually solved the problem, thanks a lot!
