### ISSUE TITLE
Suggestion: Function for Codebook

### ISSUE THREAD

**Issue by cschwem2er** [ManifestoProject/manifestoR#2]
Hi,

first of all many thanks for creating this R package, which makes it really convenient to extract manifesto data. There is only one feature that I really regret not to have, and that is a function for accessing the manifesto codebook. 
A function for this could simply return a (or more than one) dataframe containing all the codes and the corresponding explanations as included in the  [PDF Codebook](https://manifesto-project.wzb.eu/down/data/2017a/codebooks/codebook_MPDataset_MPDS2017a.pdf)

**Comment by nicmer** [comment]
thanks for the suggestions. we are working on this and plan to implement something like this with the next release of the main dataset at the end of this year.

**Comment by hdigital** [comment]
Same here, I have been working with the manifesto data, have been impressed by its evolution and would like to have a dataset with the categories from the codebook as well.

**Comment by nicmer** [comment]
Version 1.3 (already on CRAN, 
not yet on github) introduces three new functions to implement the desidered functionality:


<img width="746" alt="screenshot 2018-05-29 09 04 33" src="https://user-images.githubusercontent.com/5261439/40643670-36a1e740-6321-11e8-92e5-021dde9a2dff.png">

<img width="737" alt="screenshot 2018-05-29 09 03 56" src="https://user-images.githubusercontent.com/5261439/40643689-43ba0124-6321-11e8-9c0a-862c84a0d46c.png">

 mp_view_codebook() opens a searchable table in the viewer pane:
<img width="668" alt="screenshot 2018-05-29 09 04 13" src="https://user-images.githubusercontent.com/5261439/40643734-5eb82866-6321-11e8-8a53-02fd4c940051.png">

**Comment by nicmer** [comment]
praise @jirkalewandowski for implementing these functions.
