### ISSUE TITLE
JSON request does not work. API documentation up to date?

### ISSUE THREAD

**Issue by MoritzLaurer** [ManifestoProject/manifestoR#6]
Thanks a lot for creating this amazing dataset and package. I'm trying to obtain the data via a JSON request in python (instead of the R package) and most functions described in the API description work except for `api_metadata` and 'api_texts_and_annotations'.  see here: https://manifesto-project.wzb.eu/information/documents/api

I'm wondering if I'm misunderstanding the JSON request format, or if the documentation might be a bit unclear. 
The documentation says: 

> api_metadata: get corpus metadata for a list of parties in elections
>     parameter: keys (e.g. "keys[]=41320_200909&keys[]=41320_200509"); valid key values are provided by api_get_core, but you need to combine the party and the date column

When I use the exact example request "keys[]=41320_200909" (with or without the [], with or without the "s" of "keys"), I always get a 404 error response. My impression is that the input for the keys argument is not correct, but I tried many variations of the exact examples and it doesn't work.

```
url = f"https://manifesto-project.wzb.eu/tools/api_metadata.json"
params = dict(api_key=api_key, keys="41320_200909",
              version="MPDS2020a")
response = requests.get(url=url, params=params)
print(response)
# <Response [404]>
```

Or the pure URL request:
url = "https://manifesto-project.wzb.eu/tools/api_metadata.json?api_key=...&keys=41320_200909&version=MPDS2020a"
 
Does someone know what is going wrong? What format is required for the “keys” argument?

**Comment by MoritzLaurer** [comment]
The issue is solved. I received a clear response from the team via email, thank you very much. 
The API documentation was slightly updated and it's now clearer. (The version needs to be in the format version="2015-3" and I had made a mistake in formatting the keys[] argument)

**Comment by tburst** [comment]
A small follow up: Since api requests related to the corpus need the corpus version (for example "2020-1"), while requests related to the main dataset need the dataset version (for example "MPDS2020a"), we have explicitly added the required version type to each request in the [api documentation ](https://manifesto-project.wzb.eu/information/documents/api)

The keys variable for the corpus metadata request is correctly referenced with "keys[]". Here is a working python example:

``` 
url = "https://manifesto-project.wzb.eu/tools/api_metadata.json"
response = requests.post(url=url, data={"api_key":api_key, "keys[]":"41320_200909", "version":"2020-1",})
print(response)
# <Response [200]>```
