### ISSUE TITLE
Unknown code in the manifestoR data (for Germany)

### ISSUE THREAD

**Issue by hungnguyen167** [ManifestoProject/manifestoR#7]
Dear developers,

I was working with German data today when I found "H" among the codes, specifically for the case of the SPD party in Germany. I checked the codebook using the function mp_codebook but "H" isn't one of the recognized codes. Could you please check and correct the data, or at least let me know what "H" means? 

Replication codes: 

```{r spd}
mp_use_corpus_version("2020-2")
corpus_germany <- mp_corpus(countryname == "Germany" & year >= "1988")

spd_1998 <- corpus_germany[["41320_199809"]]$content %>%
  mutate(pos = row_number()) %>%
  rename(code = cmp_code) %>%
  select(text, code, pos)
spd_2002 <- corpus_germany[["41320_200209"]]$content %>%
  mutate(pos = row_number()) %>%
  rename(code = cmp_code) %>%
  select(text, code, pos)
spd_2005 <- corpus_germany[["41320_200509"]]$content %>%
  mutate(pos = row_number()) %>%
  rename(code = cmp_code) %>%
  select(text, code, pos)
spd_2009 <- corpus_germany[["41320_200909"]]$content %>%
  mutate(pos = row_number()) %>%
  rename(code = cmp_code) %>%
  select(text, code, pos)
spd_2013 <- corpus_germany[["41320_201309"]]$content %>%
  mutate(pos = row_number()) %>%
  rename(code = cmp_code) %>%
  select(text, code, pos)
spd_2017 <- corpus_germany[["41320_201709"]]$content %>%
  mutate(pos = row_number()) %>%
  rename(code = cmp_code) %>%
  select(text, code, pos)

spd <- rbind(spd_1998, spd_2002, spd_2005, spd_2009, spd_2013, spd_2017)
spd$code <- ifelse(is.na(spd$code), "Unknown", spd$code)
unique(spd$code)
``` 
Now, among the codes, you would find "Unknown", which are basically recoded NAs, and "H", which I'm not sure to which category they belong to. 

I look forward to your support!

Thank you and best regards,
Hung.

**Comment by tburst** [comment]
The H codes mark headlines in the document, so they do not belong to any category.  For some applications it is certainly helpful to know about the formatting and structure of the document, but regarding the manifesto categories they can also be understood as NAs.
